jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build D:\a\DatingApp\DatingApp\API\API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish D:\a\DatingApp\DatingApp\API\API.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish

      - name: Verify publish output
        run: |
          echo "Listing contents of the publish directory:"
          ls -la $(Build.ArtifactStagingDirectory)/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: $(Build.ArtifactStagingDirectory)/publish
